---
- hosts: localhost
  vars_files:
    - var_stuff.yml
#  vars:
#    image_name: Nidhi_Redhat_6_7 
#    instance_name: Nidhi_Redhat_6_7
  tasks:
#  - name: Downloading  OS image  qcow2
#    get_url: url="{{ url_image }}"  dest=/opt/abhay/project/redhat_6_T2/image1

  - name: Exporting variables
    shell: source /opt/abhay/project/redhat_6_T2/script.sh 

  - name: Listing image1 files
    find: 
      paths: "/opt/abhay/project/redhat_6_T2/image1/"
    register: found_file
  

#  - name: Creating cloud image from qcow2
#    shell: /bin/openstack --insecure  image create {{ image_name }} --disk-format qcow2  --private  --min-disk 40 --file "{{ found_file.files[0].path }}"
 
#  - name: Sleeping for 15 mins
#    shell: sleep 900

  - name: Create keypair
    shell: openstack keypair create mykey-$instance_name > /opt/abhay/project/redhat_6_T2/mykey-$instance_name.pem

  - name: Changing key file permission
    shell: chmod 600 /opt/abhay/project/redhat_6_T2/mykey-$instance_name.pem

  - name: Creating instance from image
    shell: /bin/openstack --insecure server create --flavor t2.micro --image {{ image_name }} \
             --key-name mykey-$instance_name --nic net-id=1fd7a904-2367-4a43-ae49-1351588387d6 \
             --security-group default {{ instance_name }}
