---
- hosts: all
  remote_user: cloud
  become: True
  vars_files:
    - var_stuff.yml

  tasks:
#######################################################################333

  - name: Deleting lines for centos user
    lineinfile: 
      dest: /etc/cloud/cloud.cfg
      state: absent
      regexp: 'runcmd:'

  - name: Deleting lines for centos user
    lineinfile: 
      dest: /etc/cloud/cloud.cfg
      state: absent
      regexp: 'centos'

  - name: Setting root password
    shell: echo "redhat" | passwd --stdin "root"

  - name: Deleting lines for host from /etc/hosts
    lineinfile:
      dest: /etc/hosts
      state: absent
      regexp: "{{ instance_name }}"

  - name: Deleting remaining lines for host from /etc/hosts
    lineinfile:
      dest: /etc/hosts
      state: absent
      regexp: "^192."

  - name: Making entry in /etc/hosts
    shell: echo "%LOCALIPV4%  %LOCALHOSTNAME%" >> /etc/hosts

  - name:  Clear history
    shell: echo "">/root/.bash_history
    ignore_errors: yes
  
  - name:  Clear history
    shell: echo "">/home/cloud/.bash_history
    ignore_errors: yes

  - name: Run history -c
    shell: history -c
    ignore_errors: yes

  - name: Deleting /var/lib/cloud directory
    shell: rm -rf /var/lib/cloud/*
    ignore_errors: yes

  - name: Clear auth files and logs for root
    shell: echo "">/root/.ssh/authorized_keys
    ignore_errors: yes

  - name: Clear auth files and logs for non root
    shell: echo "">/home/cloud/.ssh/authorized_keys
    ignore_errors: yes

  - name: Clear /var/log/*
    shell: rm -rf /var/log/*

  - name: Clear history
    shell: history -w;echo > /root/.bash_history;history -c;history -c;history -c
    ignore_errors: yes

  - name: Doing blank on hosts file
    shell: echo"">/opt/abhay/project/centos_7/hosts
    delegate_to: localhost

  - name: Delete all blank lines in hosts file
    shell: sed -i '/^$/d' /opt/abhay/project/centos_7/hosts
    delegate_to: localhost
