---
- hosts: localhost
  tasks:

  - name: Creating EIP
    shell: openstack floating ip create 0a2228f2-7f8a-45f1-8e09-9039e1d09975
    register: var_EIP

  - name: Assign EIP to server
    shell: openstack server add floating ip {{ instance_name }} {{ var_EIP.stdout_lines[6].split('|')[2] }}
  
  - name: Getting fixed EIP
    shell: openstack server show {{ instance_name }}
    register: var_fixip
  
  - name: Doing entry on host file
    lineinfile: path=/opt/abhay/project/centos_7_4/hosts line='{{ var_fixip.stdout_lines[15].split('|')[2].split('=')[1].split(',')[0] }} ansible_ssh_private_key_file=/root/abhay/abhay_keys/KeyPair-1c48_abhay_prod.pem'
