---
- hosts: all
  remote_user: cloud
  become: True
  vars_files:
    - "/opt/abhay/project/globalImageFactory/vars/var_stuff.yml"

  tasks:
#######################################################################333

  - name: Deleting lines for host from /etc/hosts
    lineinfile:
      dest: /etc/hosts
      state: absent
      regexp: "{{ instance_name }}"

  - name: Deleting remaining lines for host from /etc/hosts
    lineinfile:
      dest: /etc/hosts
      state: absent
      regexp: "^192."

  - name: Making entry in /etc/hosts
    shell: echo "%LOCALIPV4%  %LOCALHOSTNAME%" >> /etc/hosts

  - name:  Clear history
    shell: echo "">/root/.bash_history
    ignore_errors: yes
  
  - name:  Clear history
    shell: echo "">/home/cloud/.bash_history
    ignore_errors: yes

  - name: Run history -c
    shell: history -c
    ignore_errors: yes

  - name: Deleting /var/lib/cloud directory
    shell: rm -rf /var/lib/cloud/*
    ignore_errors: yes

  - name: Clear auth files and logs for root
    shell: echo "">/root/.ssh/authorized_keys
    ignore_errors: yes

  - name: Clear auth files and logs for non root
    shell: echo "">/home/cloud/.ssh/authorized_keys
    ignore_errors: yes

  - name: Clear /var/log/*
    shell: rm -rf /var/log/*
    ignore_errors: yes

  - name: Clear history
    shell: history -w;echo > /root/.bash_history;history -c;history -c;history -c
    ignore_errors: yes

  - name: Doing blank on hosts file
    shell: echo"">/opt/abhay/project/globalImageFactory/"{{ instance_name }}"/hosts
    delegate_to: localhost

  - name: Delete all blank lines in hosts file
    shell: sed -i '/^$/d' /opt/abhay/project/globalImageFactory/"{{ instance_name }}"/hosts
    delegate_to: localhost

  - name: Creating success file
    file:
      path: /opt/abhay/project/globalImageFactory/{{ instance_name }}/clearAllLogs_success
      state: touch
    delegate_to: localhost
